version: '3'

services:
#  app:
#    build:
#      context: ../
#      dockerfile: docker/Dockerfile
#    command: ./entrypoint.sh
#    volumes:
#      - ../:/usr/src/app
#    ports:
#      - "8000:8000"
#    links:
#      - db
#    depends_on:
#      - db
#      - redis

  redis:
    image: redis

  db:
    image: postgres
    volumes:
      - ../../data/development:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cm_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
